# Site settings
title: НП групп
email: sarhov@sarhov.com
description:  Автомобильные грузоперевозки
slogan:  Ваш надежный партнер в мире грузоперевозок!
baseurl: "/np_groups/"
url: "./" # the base hostname & protocol for your site
paginate_path: "news/page:num/"
github_username:  sarhov
paginate: 3
# Build settings
markdown: kramdown
include:      ["*.scss"]
exclude: ["*.sublime-project", "*.sublime-workspace"]
collections:
  autopark:
    output: true
  guarantees:
    output: true  
  news:
    output: true    
  articles:
    output: true      
  prices:
    output: true  
